import Head from 'next/head';
import { useRouter } from 'next/router';
import { manakit } from '../plugins/manakit';
import { App, Footer, Icon, Main, Spacer, Toolbar } from 'manakit';

import Home from './template/Home';
import DocsPage from './template/Documentation';
import { mdiDisqus, mdiGithub, mdiNpm, mdiTwitter } from '@mdi/js';

export default function MyApp() {
  const router = useRouter();

  console.log('router', router);
  return (
    <App theme={manakit}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>{router.pathname === '/' ? <Home /> : <DocsPage />}</Main>
      <Footer app className={'justify-center'}>
        <a href="https://github.com/manastone" target={'_blank'} className={'primary--text d-inline-block mx-2 '}>
          <Icon>{mdiGithub}</Icon>
        </a>
        <a
          href="https://www.npmjs.com/org/manastone"
          target={'_blank'}
          className={'primary--text d-inline-block mx-2 '}
        >
          <Icon>{mdiNpm}</Icon>
        </a>
        <a href="https://manastone.fr" target={'_blank'} className={'d-inline-block mx-2 '}>
          <img src="/logo/Manastone_Logo_Color_Dark.png" width={64} height={64} />
        </a>
        <a href="https://twitter.com/ManastoneDev" target={'_blank'} className={'primary--text d-inline-block mx-2 '}>
          <Icon>{mdiTwitter}</Icon>
        </a>
        <a
          href="https://discord.com/invite/24pTEehYbQ"
          target={'_blank'}
          className={'primary--text d-inline-block mx-2 '}
        >
          <Icon>{mdiDisqus}</Icon>
        </a>
      </Footer>
    </App>
  );
}
