// types
import { ManakitPreset } from '../../types';

export const preset: ManakitPreset = {
  ssr: false,
  theme: {
    default: 'light',
    disable: false,
    themes: {
      light: {
        primary: '#6750A4',
        //primaryContainer: '#EADDFF',
        secondary: '#625B71',
        //secondaryContainer: '#E8DEF8',
        tertiary: '#7D5260',
        // tertiaryContainer: '#FFD8E4',
        surface: '#FFFBFE',
        //surfaceVariant: '#E7E0EC',
        background: '#FFFBFE',
        error: '#B3261E',
        //errorContainer: '#F9DEDC',
        //onPrimary: '#FFFFFF',
        // onPrimaryContainer: '#21005E',
        // onSecondary: '#FFFFFF',
        // onSecondaryContainer: '#1E192B',
        // onTertiary: '#FFFFFF',
        // onTertiaryContainer: '#370B1E',
        // onSurface: '#1C1B1F',
        // onSurfaceVariant: '#49454E',
        // onError: '#FFFFFF',
        // onErrorVariant: '#410E0B',
        // onBackground: '#1C1B1F',
        outline: '#79747E',
        //outlineVariant: '#C4C7C5',
        shadow: '#000000',
        text: '#1C1B1F',
        //surfaceTint: '#6750A4',
        //inverseSurface: '#313033',
        // inverseOnSurface: '#F4EFF4',
        // inversePrimary: '#D0BCFF',
        //scrim: '#000000',
      },
      dark: {
        primary: '#D0BCFF',
        //primaryContainer: '#4F378B',
        secondary: '#CCC2DC',
        //secondaryContainer: '#4A4458',
        tertiary: '#EFB8C8',
        //tertiaryContainer: '#633B48',
        surface: '#1C1B1F',
        //surfaceVariant: '#49454F',
        background: '#1C1B1F',
        error: '#F2B8B5',
        // errorContainer: '#8C1D18',
        // onPrimary: '#371E73',
        // onPrimaryContainer: '#EADDFF',
        // onSecondary: '#332D41',
        // onSecondaryContainer: '#E8DEF8',
        // onTertiary: '#492532',
        // onTertiaryContainer: '#FFD8E4',
        // onSurface: '#E6E1E5',
        // onSurfaceVariant: '#CAC4D0',
        // onError: '#601410',
        // onErrorVariant: '#F9DEDC',
        // onBackground: '#E6E1E5',
        outline: '#938F99',
        // outlineVariant: '#444746',
        shadow: '#000000',
        text: '#E6E1E5',
        // surfaceTint: '#D0BCFF',
        // inverseSurface: '#E6E1E5',
        // inverseOnSurface: '#313033',
        // inversePrimary: '#6750A4',
        // scrim: '#000000',
      },
    },
  },
};
